### ISSUE TITLE
Request for ubx format data

### ISSUE THREAD

**Issue by fenrir-naru** [MeijoMeguroLab/open_data#1]
Thank you for publishing great data.
I think it will be useful to publish GNSS data not only in RINEX format but also u-blox format if available.

**Comment by JunichiMeguro** [comment]
Please wait while we get ready. We can be ready in a few days.

**Comment by takahirokashimoto** [comment]
@fenrir-naru 
GNSS data in u-blox format has been added to the dataset.
Please download it from the link I provided.

**Comment by JunichiMeguro** [comment]
We have included ubx in the data.
